name: Daily Attendance

on:
  schedule:
    # 00:00 UTC
    - cron: '0 0 * * *'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  attendance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Linting
        run: pnpm lint

      - name: Run attendance
        run: pnpm dev
        env:
          ACCOUNT_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}
