name: Repository Keepalive

on:
  schedule:
    # every sunday
    - cron: '0 0 * * 0'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Check inactivity
        id: inactivity
        run: |
          LAST=$(git log -1 --format=%ct)
          NOW=$(date +%s)
          DAYS=$(( (NOW - LAST) / 86400 ))

          echo "days=$DAYS" >> "$GITHUB_OUTPUT"

      - name: Create keepalive commit
        if: steps.inactivity.outputs.days >= 50
        run: |
          git commit --allow-empty -m "chore: keepalive"
          git push
